import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserProvider } from "./UserContext";


export const metadata = {
  title: "Shipping System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en-ar"
      className="h-full antialiased"
      dir="rtl"
    >
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200..1000&display=swap" rel="stylesheet" />
      </head>
      <body style={{ fontFamily: "Cairo" }} className="min-h-full flex flex-col">
        {
          <UserProvider>
            {children}
          </UserProvider>
        }
      </body>
    </html>
  );
}
